### ISSUE TITLE
Planejar próximo ciclo de Tech Talks

### ISSUE THREAD

**Issue by piantino** [saibrotech/mentoria#104]
### TechTalks

- [x] ETL no sebrae - @nanipumpkin - 23/08/23
- [x] APIs e documentação, usando como modelo o do Google - @Nibuitoni  - 30/08/23
- [x] Backend com Django - @piantino - 05/08/23
- [x] Conceitos para modelagem de BD e API - @piantino - 18/09/2023
- [x] API com Django - @nilljr  - https://github.com/saibrotech/mentoria/issues/182
- [x] Desenvolvimento mobile com React Native - @AndreBuitoni - https://github.com/saibrotech/mentoria/issues/169
- [x] Protótipo Drinkifyme - Paulinha [#183]

**Comment by piantino** [comment]
@nilljr , @AndreBuitoni e @PaulaBuitoni peço que marquem a data de apresentação do que desenvolveram no projeto.
Sugestão, segunda dia 4 ou 11 de desembro.
